#!/usr/bin/env php

<?php 

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputArgument;

require 'vendor/autoload.php';

$app = new Application('Symfony Script Example One', '1.0');

$app->register('sayHelloWorldTo')
    ->setDescription('Is going to say hello back')
    ->addArgument('name', InputArgument::REQUIRED, 'Your name.')
    ->setCode(function(InputInterface $input, OutputInterface $output)
    {
	$message = "Hello, " . $input->getArgument('name');

	$output->writeln("<info>{$message}</info>");
    });

$app->run();
