#!/usr/bin/env php

<?php 

use Acme\SayHelloCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Symfony Script Example One', '1.0');

// $app->register('sayHelloWorldTo');

$app->add(new SayHelloCommand);

$app->run();

